# Generated by Django 5.1 on 2024-10-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_book_is_banned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
    ]
